/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.57
 * Generated at: 2020-11-29 13:06:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.exam;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class list_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/C:/soo/A_TeachingMaterial/7.LastProject/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ddit/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/exam/registForm_js.jsp", Long.valueOf(1606565342130L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1602513789311L));
    _jspx_dependants.put("jar:file:/C:/soo/A_TeachingMaterial/7.LastProject/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ddit/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<div class=\"content-body\" >\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("   <!-- Page Headings Start -->\r\n");
      out.write("   <div class=\"row justify-content-between align-items-center mb-10\">\r\n");
      out.write("       <!-- Page Heading Start -->\r\n");
      out.write("       <div class=\"col-12 col-lg-auto mb-20\">\r\n");
      out.write("           <div class=\"page-heading\">\r\n");
      out.write("           \t<h3 class=\"title\" style=\"text-align: left;\">시험문제관리</h3>\r\n");
      out.write("           </div>\r\n");
      out.write("       </div><!-- Page Heading End -->\r\n");
      out.write("\r\n");
      out.write("   </div><!-- Page Headings End -->\r\n");
      out.write("      \r\n");
      out.write("\t<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"col-12 col-lg-auto mb-20\">\r\n");
      out.write("<!-- \t\t\t시험선택 -->\r\n");
      out.write("<!-- \t\t\t<select id=\"test_name\" onChange=\"changeTest(this)\"> -->\r\n");
      out.write("<!-- \t\t\t\t<option value=\"\" selected>선택하세요</option> -->\r\n");
      out.write("<!-- \t\t\t</select> -->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t <script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\tvar examList= new Array();\r\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvar exampleList= new Array();\r\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("</script>\r\n");
      out.write("\t\t\t\r\n");
      out.write("<form action=\"modify.do\" method=\"post\" name=\"modifyForm\">\r\n");
      out.write("\t\t\t<div id=\"start\">\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("    <div id=\"followquick\">\r\n");
      out.write("    <div style=\"text-align: center;\">총 점</div>\r\n");
      out.write("    ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("<button type=\"button\" class=\"button button-round button-dark\" id=\"backBtn\">뒤로가기</button>\r\n");
      out.write("</div> \r\n");
      out.write("\r\n");
      out.write("            \r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<input type=\"hidden\" name=\"test_name\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${test_no2}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("<script>\r\n");
      out.write("// \t선택한 시험지 로드\r\n");
      out.write("\t$(document).ready(function(){\r\n");
      out.write("\r\n");
      out.write("// \t\talert($('input[name=test_name]').val());\r\n");
      out.write("\t\tchangeTest(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${test_no2}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar point = $('input[name=exam_point]');\r\n");
      out.write("\t\tvar sumpoint=0;\r\n");
      out.write("\t\tfor (var i = 0; i < point.length; i++) {\r\n");
      out.write("\t\t\tsumpoint += Number($('input[name=exam_point]').eq(i).val());\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t$('#sumPoint').val(sumpoint);\r\n");
      out.write("\t\r\n");
      out.write("\t});\t\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script>\t\t\r\n");
      out.write("\tfunction changeTest(ele){ //시험지 변경\t\t\r\n");
      out.write("\t\t$('#start').empty();\r\n");
      out.write("\t\t\r\n");
      out.write("// \t\talert(examList.length);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar testNo = ele;\t\t\r\n");
      out.write("\r\n");
      out.write("\t\tvar ab= 0;\r\n");
      out.write("\t\tvar ac = 0;\r\n");
      out.write("\t\tfor (var i = 0; i < examList.length; i++) {\t\t\t\r\n");
      out.write("\t\t\tif((examList[i].test_no)==testNo){\t\t\t\t\r\n");
      out.write("\t\t\t\t$('#start').append(\"<div id='exam' name='exam' class='answer'>\"+\r\n");
      out.write("\t\t\t\t\t\t'<div id=\"examDiv\" name=\"examDiv2\">문제번호<input type=\"number\" maxlength=\"3\" name=\"exam_no\" id=\"exam_no\" class=\"form-control2 answer_num\" oninput=\"maxLengthCheck(this)\">배점<input type=\"number\" name=\"exam_point\" class=\"answer_point\" maxlength=\"3\" oninput=\"maxLengthCheck(this)\">정답<input type=\"text\" name=\"exam_answer\" class=\"answer_answer\">'+\r\n");
      out.write("\t\t\t\t\t\t'문제유형<select onChange=\"selectExamCate(this)\" name=\"exam_category_no\" class=\"exampleType\"><option value=\"ss\" selected>선택하세요</option> <option value=\"EXAMCATE001\">객관식</option><option value=\"EXAMCATE002\">주관식</option><option value=\"EXAMCATE003\">서술식</option></select><button type=\"button\" id=\"examDelete\" class=\"delete_btn\"><i class=\"fa fa-trash-o\" aria-hidden=\"true\"></i>&#160;삭제</button><br>'+\r\n");
      out.write("\t\t\t\t\t\t'문제제목<input type=\"text\" name=\"exam_title\" class=\"answerTitle\" ><input type=\"hidden\" name=\"test_no\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${test_no2}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"><input type=\"hidden\" name=\"exam_id\">'+\r\n");
      out.write("\t\t\t\t\t\t\"<div id='example'></div>\"+\"</div>\");\r\n");
      out.write("\t\t\t\t$(\"input[name=exam_title]\").eq(ab).val(examList[i].exam_title);\r\n");
      out.write("\t\t\t\t$(\"input[name=exam_no]\").eq(ab).val(examList[i].exam_number);\t\t\t\t\r\n");
      out.write("\t\t\t\t$(\"input[name=exam_point]\").eq(ab).val(examList[i].exam_point);\r\n");
      out.write("\t\t\t\t$(\"select[name=exam_category_no] option[value=\"+examList[i].exam_category_no+\"]\").eq(ab).attr(\"selected\", true);\t\t\t\t\r\n");
      out.write("\t\t\t\t$(\"input[name=exam_answer]\").eq(ab).val(examList[i].exam_answer);\r\n");
      out.write("\t\t\t\t$(\"input[name=exam_id]\").eq(ab).val(examList[i].exam_no);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvar z=0;\r\n");
      out.write("\t\t\t\tfor (var y = 0; y < exampleList.length; y++) {\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tif(examList[i].exam_no==exampleList[y].exam_no){\r\n");
      out.write("// \t\t\t\t\t\talert(i);\r\n");
      out.write("// \t\t\t\t\t\talert(y);\r\n");
      out.write("// \t\t\t\t\t\talert(z);\r\n");
      out.write("// \t\t\t\t\t\talert(exampleList[y].example_content);\r\n");
      out.write("\t\t\t\t\t\tvar thisExamNumber = $(\"input[name=exam_no]\").eq(ab).val();\r\n");
      out.write("// \t\t\t\t\t\talert(thisExamNumber);\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tif(z==0){\r\n");
      out.write("\t\t\t\t\t\t\t$(\"div[name=examDiv2]\").eq(ab).append(\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t'<div id=\"exampleDiv\"><ol><li><div><input type=\"radio\" name=\"exampleNum\" ><input type=\"text\" name=\"example_content\" class=\"example_cont\">'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t+'<input type=\"hidden\" name=\"example_no\"><button type=\"button\" id=\"exampleAdd\"><i class=\"zmdi zmdi-brush zmdi-hc-fw\"></i></button><input type=\"hidden\" name=\"exam_no2\"  value=\"'+thisExamNumber+'\"><input type=\"hidden\" name=\"exam_id2\"><div></li></ol></div>');\r\n");
      out.write("\t\t\t\t\t\t\tz++;\r\n");
      out.write("\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\t$(\"div[name=examDiv2]\").eq(ab).children().children('ol').append(\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t'<li><div><input type=\"radio\" name=\"exampleNum\" ><input type=\"text\" name=\"example_content\" class=\"example_cont\">'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t+'<input type=\"hidden\" name=\"example_no\"><input type=\"hidden\" name=\"exam_id2\"><input type=\"hidden\" name=\"exam_no2\" value=\"'+thisExamNumber+'\"><button type=\"button\" id=\"exampleDelete\"><i class=\"zmdi zmdi-block zmdi-hc-fw\"></i></button><div></li>');\r\n");
      out.write("\t\t\t\t\t\t\tz++;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tfor (var x = 0; x < exampleList.length; x++) {\r\n");
      out.write("\t\t\t\t\tif(exampleList[x].exam_no==examList[i].exam_no){\r\n");
      out.write("//\t\t\t\t \t\t\talert(exampleList[x].example_content);\r\n");
      out.write("\t\t\t\t\t\t$(\"input[name=example_content]\").eq(ac).val(exampleList[x].example_content);\r\n");
      out.write("\t\t\t\t\t\t$(\"input[name=example_no]\").eq(ac).val(exampleList[x].example_no);\r\n");
      out.write("\t\t \t\t\t\tac++;\t\r\n");
      out.write("\t\t\t\t\t}\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tab++;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\t\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tfunction selectExamCate(ele){ //문제 카테고리 변경\r\n");
      out.write("\t\t//문제번호 입력시에 선택가능\r\n");
      out.write("\t\tvar btn = $(ele);\t\t\r\n");
      out.write("\t\tvar exam_no_val = btn.parent().children('#exam_no').val()\r\n");
      out.write("\t\tif(exam_no_val==\"\"){\r\n");
      out.write("\t\t\talert('문제번호를 먼저 입력해주세요');\r\n");
      out.write("// \t\t\t$(\"select[name=exam_category_no] option[value=\"+examList[i].exam_category_no+\"]\").eq(ab).attr(\"selected\", true);\t\r\n");
      out.write("\t\t\t$(ele).parent().children('select').find('option:first').attr('selected',false);\r\n");
      out.write("\t\t\t$(ele).parent().children('select').find('option:first').attr('selected','selected');\r\n");
      out.write("\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//문제유형 변경시 지우기\r\n");
      out.write("\t\tvar examObject = btn.parent().parent(); //exam\r\n");
      out.write("\t\texamObject.children('#examDiv').children().remove(\"#exampleDiv\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar examDiv = btn.parent(); //examDiv\r\n");
      out.write("\t\tvar thisExamNumber = btn.parent().children(\"#exam_no\").val(); //문제번호 input\r\n");
      out.write("\r\n");
      out.write("\t\tvar ele = $(ele);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(ele.val()==\"EXAMCATE001\"){\r\n");
      out.write("\t\t\texamDiv.append('<div id=\"exampleDiv\"><ol><li><div><input type=\"radio\" name=\"exampleNum\" ><input type=\"text\" name=\"example_content\" class=\"example_cont\">'\r\n");
      out.write("\t\t\t\t+'<input type=\"hidden\" name=\"exam_no2\" value=\"'+thisExamNumber+'\"><button type=\"button\" id=\"exampleAdd\"><i class=\"zmdi zmdi-brush zmdi-hc-fw\"></i></button><div></li></ol></div>');\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t$(document).on('click', '#examDelete', function(){\r\n");
      out.write("\t\tvar btn = $(this);\r\n");
      out.write("\t\tvar div = btn.parent(); //examDiv\r\n");
      out.write("\t\tbtn.parent().remove();\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(document).on('click', '#exampleDelete', function(){\r\n");
      out.write("\t\tvar btn = $(this);\r\n");
      out.write("\t\tvar div = btn.parent().parent(); \r\n");
      out.write("\t\tdiv.remove();\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t$(document).on('click', '#exampleAdd', function(){\r\n");
      out.write("\t\tvar btn = $(this);\r\n");
      out.write("\t\tvar div = btn.parent().parent().parent(); //examDiv - ol\r\n");
      out.write("// \t\talert(btn.parent().parent().parent().text());\r\n");
      out.write("\t\tvar thisExamNumber = btn.parent().parent().parent().parent().parent().children(\"#exam_no\").val(); //문제번호 input\r\n");
      out.write("\t\talert(thisExamNumber);\r\n");
      out.write("\t\tdiv.append('<li><div><input type=\"radio\" name=\"exampleNum\"><input type=\"text\" name=\"example_content\" class=\"example_cont\"><button type=\"button\" id=\"exampleDelete\"><i class=\"zmdi zmdi-block zmdi-hc-fw\"></i></button><input type=\"hidden\" name=\"exam_no2\" value=\"'+thisExamNumber+'\"></div></li>');\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t//시험문제 추가\r\n");
      out.write("\t$('#addBtn').on('click',function(){\r\n");
      out.write("\t\tvar testName = $('#test_name').val();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('#start').append(\"<div id='exam' name='exam' class='answer'>\"+\r\n");
      out.write("\t\t'<div id=\"examDiv\">문제번호<input type=\"number\" name=\"exam_no\" id=\"exam_no\" class=\"answer_num\" maxlength=\"3\" oninput=\"maxLengthCheck(this)\">배점<input type=\"number\" name=\"exam_point\" class=\"answer_point\" maxlength=\"3\" oninput=\"maxLengthCheck(this)\">정답<input type=\"text\" name=\"exam_answer\" class=\"answer_answer\">'+\r\n");
      out.write("\t\t'문제유형<select onChange=\"selectExamCate(this)\" name=\"exam_category_no\" class=\"exampleType\"><option value=\"ss\" selected>선택하세요</option> <option value=\"EXAMCATE001\">객관식</option><option value=\"EXAMCATE002\">주관식</option><option value=\"EXAMCATE003\">서술식</option></select><button type=\"button\" id=\"examDelete\" class=\"delete_btn\"><i class=\"fa fa-trash-o\" aria-hidden=\"true\"></i>&#160;삭제</button><br>'+\r\n");
      out.write("\t\t'문제제목<input type=\"text\" name=\"exam_title\" class=\"answerTitle\"><input type=\"hidden\" name=\"test_no\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${test_no2}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></div>'+\r\n");
      out.write("\t\t\"<div id='example'></div>\"\t\r\n");
      out.write("\t\t+\"</div><hr>\");\r\n");
      out.write("// \t\talert($('input[name=test_name]').val()); //시험번호 히든 값 테스트\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\tfunction maxLengthCheck(object){\r\n");
      out.write("\t    if (object.value.length > object.maxLength){\r\n");
      out.write("\t      object.value = object.value.slice(0, object.maxLength);\r\n");
      out.write("\t    }    \r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t$(document).on(\"propertychange change keyup paste input\", 'input[name=exam_point]', function() {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar point = $('input[name=exam_point]');\r\n");
      out.write("\t\tvar sumpoint=0;\r\n");
      out.write("\t\tfor (var i = 0; i < point.length; i++) {\r\n");
      out.write("\t\t\tsumpoint += Number($('input[name=exam_point]').eq(i).val());\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t$('#sumPoint').val(sumpoint);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${test.test_score }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("<sumpoint){\r\n");
      out.write("\t\t\talert(\"입력한 점수가 총점을 초과하였습니다.\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\t.answer{\r\n");
      out.write("\t\tmargin-bottom: 10px;\r\n");
      out.write("/* \t\tborder:1px solid black; */\r\n");
      out.write("\t\tmargin-left:200px;\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\t.answer_num, .answer_point{\r\n");
      out.write("\t\twidth:70px;\r\n");
      out.write("\t\tmargin-right:10px;\r\n");
      out.write("\t\tmargin-bottom:5px;\r\n");
      out.write("\t\tborder:none;\r\n");
      out.write("\t\tborder-bottom : 1px solid #dadce0;\r\n");
      out.write("\t}\r\n");
      out.write("\t.answer_answer{\r\n");
      out.write("\t\tmargin-right:10px;\r\n");
      out.write("\t\twidth:150px;\r\n");
      out.write("\t\tborder:none;\r\n");
      out.write("\t\tborder-bottom : 1px solid #dadce0;\r\n");
      out.write("\t}\r\n");
      out.write("\t.exampleType{\r\n");
      out.write("\t\theight:30px;\r\n");
      out.write("\t\tmargin-right:213px;\r\n");
      out.write("\t\tborder:none;\r\n");
      out.write("\t\tborder-bottom : 1px solid #dadce0;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.answerTitle{\r\n");
      out.write("\t\twidth: 800px;\r\n");
      out.write("\t\theight: 40px;\t\t\r\n");
      out.write("\t\tmargin-bottom: 10px;\r\n");
      out.write("\t\tborder:none;\r\n");
      out.write("\t\tborder-bottom : 1px solid #dadce0;\r\n");
      out.write("\t}\r\n");
      out.write("\t.example_cont{\r\n");
      out.write("\t\twidth:500px;\r\n");
      out.write("\t\tmargin-bottom: 5px;\r\n");
      out.write("\t\tborder:none;\r\n");
      out.write("\t\tborder-bottom : 1px solid #dadce0;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.delete_btn, #exampleAdd, #exampleDelete{\t\t\r\n");
      out.write("\t\tbackground-color: rgba(0,0,0,0);\r\n");
      out.write("\t\tborder:none;\r\n");
      out.write("\t\tpadding-right:20px;\r\n");
      out.write("\t\tfont-size:15px;\r\n");
      out.write("\t}\r\n");
      out.write("\t#examDiv{\r\n");
      out.write("\t\tborder : 2px solid #dadce0;\r\n");
      out.write("\t\tborder-left-width: 10px;\r\n");
      out.write("\t\tborder-left-color: #4285f4;\r\n");
      out.write("\t\tpadding-left: 10px;\r\n");
      out.write("\t\tborder-radius: 10px;\r\n");
      out.write("\t\tmargin-bottom: 20px;\r\n");
      out.write("\t\tbox-shadow: 5px 3px 5px gray;\r\n");
      out.write("\t}\r\n");
      out.write("\tinput{\r\n");
      out.write("\t\tmargin-left: 5px;\r\n");
      out.write("\t\tmargin-top:10px;\r\n");
      out.write("\t}\r\n");
      out.write("\tselect{\r\n");
      out.write("\t\tmargin-left: 10px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.pointBox{\r\n");
      out.write("\t\twidth:35px;\r\n");
      out.write("\t\tmargin-right:10px;\r\n");
      out.write("\t\tmargin-bottom:5px;\r\n");
      out.write("\t\tborder:none;\r\n");
      out.write("\t\tborder-bottom : 1px solid #dadce0;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<!-- 추가하기 스크롤바   -->\r\n");
      out.write("<style>\r\n");
      out.write("\t#followquick { position:absolute; top:220px; right:50%; margin-right:-800px; }\r\n");
      out.write("\t\r\n");
      out.write("\t.redBox{\r\n");
      out.write("\t\tborder:2px solid red;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("\t//follow quick menu\r\n");
      out.write("\t$(window).scroll(function() {\r\n");
      out.write("\t\tvar scrollTop = $(document).scrollTop();\r\n");
      out.write("\t\tif (scrollTop < 180) {\r\n");
      out.write("\t\t\tscrollTop = 180;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t$(\"#followquick\").stop();\r\n");
      out.write("\t\t$(\"#followquick\").animate({\r\n");
      out.write("\t\t\t\"top\" : scrollTop\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t$('#registBtn').on('click',function(){\r\n");
      out.write("\t\tfor (var i = 0; i < $('input[name=exam_no]').length; i++) {\r\n");
      out.write("\t\t\tif($('input[name=exam_no]').eq(i).val()==\"\"){\r\n");
      out.write("\t\t\t\talert(\"문제번호를 입력해주세요.\")\r\n");
      out.write("\t\t\t\t$('input[name=exam_no]').eq(i).focus();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\tfor (var i = 0; i < $('input[name=exam_title]').length; i++) {\r\n");
      out.write("\t\tif($('input[name=exam_title]').eq(i).val()==\"\"){\r\n");
      out.write("\t\t\talert(\"문제제목을 입력해주세요\")\r\n");
      out.write("\t\t\t$('input[name=exam_title]').eq(i).focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfor (var i = 0; i < $('select[name=exam_category_no]').length; i++) {\r\n");
      out.write("\t\tif($('select[name=exam_category_no]').eq(i).val()==\"\"){\r\n");
      out.write("\t\t\talert(\"문제유형을 선택해주세요\")\r\n");
      out.write("\t\t\t$('select[name=exam_category_no]').eq(i).focus();\r\n");
      out.write("\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfor (var i = 0; i < $('input[name=exam_point]').length; i++) {\r\n");
      out.write("\t\tif($('input[name=exam_point]').eq(i).val()==\"\"){\r\n");
      out.write("\t\t\talert(\"문제배점을 입력해주세요\")\r\n");
      out.write("\t\t\t$('input[name=exam_point]').eq(i).focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfor (var i = 0; i < $('input[name=exam_answer]').length; i++) {\r\n");
      out.write("\t\tif($('input[name=exam_answer]').eq(i).val()==\"\"){\r\n");
      out.write("\t\t\talert(\"문제정답을 입력해주세요\")\r\n");
      out.write("\t\t\t$('input[name=exam_answer]').eq(i).focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfor (var i = 0; i < $('input[name=example_content]').length; i++) {\r\n");
      out.write("\t\tif($('input[name=example_content]').eq(i).val()==\"\"){\r\n");
      out.write("\t\t\talert(\"객관식 문항의 내용을 입력해주세요\")\r\n");
      out.write("\t\t\t$('input[name=example_content]').eq(i).focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfor (var i = 0; i < $('input[name=test_name]').length; i++) {\r\n");
      out.write("\t\tif($('input[name=test_name]').eq(i).val()==\"\"){\r\n");
      out.write("\t\t\talert(\"시험지를 선택해주세요\")\r\n");
      out.write("\t\t\t$('input[name=test_name]').eq(i).focus();\r\n");
      out.write("\t\t\treturn false;\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar form = document.registForm;\r\n");
      out.write("\t\tform.submit();\t\t\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("$('#modifyBtn').on('click',function(){\r\n");
      out.write("\tfor (var i = 0; i < $('input[name=exam_no]').length; i++) {\r\n");
      out.write("\t\tif($('input[name=exam_no]').eq(i).val()==\"\"){\r\n");
      out.write("\t\t\talert(\"문제번호를 입력해주세요.\")\r\n");
      out.write("\t\t\t$('input[name=exam_no]').eq(i).focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\t\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfor (var i = 0; i < $('input[name=exam_title]').length; i++) {\r\n");
      out.write("\tif($('input[name=exam_title]').eq(i).val()==\"\"){\r\n");
      out.write("\t\talert(\"문제제목을 입력해주세요\")\r\n");
      out.write("\t\t$('input[name=exam_title]').eq(i).focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tfor (var i = 0; i < $('select[name=exam_category_no]').length; i++) {\r\n");
      out.write("\tif($('select[name=exam_category_no]').eq(i).val()==\"\"){\r\n");
      out.write("\t\talert(\"문제유형을 선택해주세요\")\r\n");
      out.write("\t\t$('select[name=exam_category_no]').eq(i).focus();\r\n");
      out.write("\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tfor (var i = 0; i < $('input[name=exam_point]').length; i++) {\r\n");
      out.write("\tif($('input[name=exam_point]').eq(i).val()==\"\"){\r\n");
      out.write("\t\talert(\"문제배점을 입력해주세요\")\r\n");
      out.write("\t\t$('input[name=exam_point]').eq(i).focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tfor (var i = 0; i < $('input[name=exam_answer]').length; i++) {\r\n");
      out.write("\tif($('input[name=exam_answer]').eq(i).val()==\"\"){\r\n");
      out.write("\t\talert(\"문제정답을 입력해주세요\")\r\n");
      out.write("\t\t$('input[name=exam_answer]').eq(i).focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tfor (var i = 0; i < $('input[name=example_content]').length; i++) {\r\n");
      out.write("\tif($('input[name=example_content]').eq(i).val()==\"\"){\r\n");
      out.write("\t\talert(\"객관식 문항의 내용을 입력해주세요\")\r\n");
      out.write("\t\t$('input[name=example_content]').eq(i).focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tfor (var i = 0; i < $('input[name=test_name]').length; i++) {\r\n");
      out.write("\tif($('input[name=test_name]').eq(i).val()==\"\"){\r\n");
      out.write("\t\talert(\"시험지를 선택해주세요\")\r\n");
      out.write("\t\t$('input[name=test_name]').eq(i).focus();\r\n");
      out.write("\t\treturn false;\t\r\n");
      out.write("\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tif(!(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${test.test_score }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("==$('#sumPoint').val())){\r\n");
      out.write("\t\talert(\"총점과 시험배점이 다릅니다.\");\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\tvar form = document.modifyForm;\r\n");
      out.write("\tform.submit();\t\t\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\t$(document).on(\"change keyup paste input\", \"input\", function() {\r\n");
      out.write("\t\t$(this).attr('style','border:1px solid rgb(118, 118, 118)');\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("$(\"#backBtn\").on('click', function(){\r\n");
      out.write("\thistory.go(-1);\r\n");
      out.write("});\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/exam/list.jsp(36,4) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/exam/list.jsp(36,4) '${examList2}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${examList2}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/exam/list.jsp(36,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("exam");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("// \t\t\t\talert(\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${exam.exam_category_no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\");\r\n");
            out.write("\t\t\t\texamList.push({\r\n");
            out.write("\t\t\t\t      exam_no:\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${exam.exam_no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\",\r\n");
            out.write("\t\t\t\t\t  test_no:\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${exam.test_no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\",\t\t\t\t\t  \r\n");
            out.write("\t\t\t\t\t  exam_category_no:\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${exam.exam_category_no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\",\r\n");
            out.write("\t\t\t\t\t  exam_title:\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${exam.exam_title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\",\r\n");
            out.write("\t\t\t\t\t  exam_point:\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${exam.exam_point}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\",\r\n");
            out.write("\t\t\t\t\t  exam_answer:\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${exam.exam_answer}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\",\r\n");
            out.write("\t\t\t\t\t  exam_status:\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${exam.exam_status}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\",\r\n");
            out.write("\t\t\t\t\t  exam_number:\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${exam.exam_number}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"\r\n");
            out.write("\t\t\t\t\t});\r\n");
            out.write("\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /WEB-INF/views/exam/list.jsp(51,4) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/exam/list.jsp(51,4) '${exampleList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${exampleList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/exam/list.jsp(51,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("example");
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\texampleList.push({\r\n");
            out.write("\t\t\t\t\t  example_no:\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${example.example_no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\",\r\n");
            out.write("\t\t\t\t\t  exam_no:\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${example.exam_no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\",\r\n");
            out.write("\t\t\t\t\t  example_content:\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${example.example_content}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\",\r\n");
            out.write("\t\t\t\t\t  example_number:\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${example.example_number}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"\t\t\t\t\t\t  \r\n");
            out.write("\t\t\t\t\t});\r\n");
            out.write("\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/exam/list.jsp(72,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.member_role eq 'PROFESSOR' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("<input type=\"text\" readonly id=\"sumPoint\" class=\"pointBox\">/<input type=\"text\" readonly id=\"totalPoint\" class=\"pointBox\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${test.test_score }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">점 <br/><br>    \r\n");
          out.write("\t<button type=\"button\" class=\"button button-round button-dark\" id=\"modifyBtn\">제출완료</button><br><br>\r\n");
          out.write("\t<button type=\"button\" class=\"button button-round button-dark\" id=\"addBtn\">문제추가</button><br><br>\r\n");
          out.write("\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/exam/list.jsp(77,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.member_role eq 'ADMIN' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("<input type=\"text\" readonly id=\"sumPoint\" class=\"pointBox\">/<input type=\"text\" readonly id=\"totalPoint\" class=\"pointBox\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${test.test_score }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">점 <br/><br>        \r\n");
          out.write("\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }
}
