/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.57
 * Generated at: 2020-11-05 14:49:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.message;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class deleteMessageBox_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/C:/soo/A_TeachingMaterial/7.LastProject/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ddit/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/message/common_message_bottom.jsp", Long.valueOf(1604587282500L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1602513789311L));
    _jspx_dependants.put("/WEB-INF/views/message/common_message_top.jsp", Long.valueOf(1604587282512L));
    _jspx_dependants.put("jar:file:/C:/soo/A_TeachingMaterial/7.LastProject/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ddit/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<body>\r\n");
      out.write("<div class=\"content-body\">\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Page Headings Start -->\r\n");
      out.write("\t<div class=\"row justify-content-between align-items-center mb-10\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t<!-- Page Heading Start -->\r\n");
      out.write("\t<div class=\"col-12 col-lg-auto mb-20\">\r\n");
      out.write("\t\t<div class=\"page-heading\">\r\n");
      out.write("\t\t\t<h3 class=\"title\" style=\"text-align: left;\">메시지</h3>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- Page Heading End -->\r\n");
      out.write("\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- Page Headings End -->\r\n");
      out.write("\t\r\n");
      out.write("\t   <!--Mail Wrapper Start-->\r\n");
      out.write("\t   <div class=\"mail-wrapper\">\r\n");
      out.write("\t\r\n");
      out.write("\t       <!--Mail Menu Start-->\r\n");
      out.write("\t       <div class=\"mail-menu\">\r\n");
      out.write("\t           <button class=\"button-compose-mail button button-danger button-round\" data-toggle=\"modal\" data-target=\"#modal-compose-mail\">메시지쓰기</button>\r\n");
      out.write("\t           <ul>\r\n");
      out.write("\t               <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/message/list\"><i class=\"zmdi zmdi-email-open\"></i>받은 메시지함</a></li>\r\n");
      out.write("\t               <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/message/sendMessageBox\"><i class=\"zmdi zmdi-mail-send\"></i>보낸 메시지</a></li>\r\n");
      out.write("\t               <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/message/notReadMessage\"><i class=\"zmdi ti-email\"></i>안읽은 메시지</a></li>\r\n");
      out.write("\t               <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/message/deleteMessageBox\"><i class=\"zmdi zmdi-delete\"></i>삭제메시지</a></li>\r\n");
      out.write("\t           </ul>\r\n");
      out.write("\t       </div>\r\n");
      out.write("\t       <!--Mail Menu End-->\r\n");
      out.write("\t\r\n");
      out.write("\t       <!--Mail List Container Start-->\r\n");
      out.write("\t       <div class=\"mail-container\">\r\n");
      out.write("\t\r\n");
      out.write("\t           <!--Mail Options Start-->\r\n");
      out.write("\t           <div class=\"mail-options\">\r\n");
      out.write("\t\r\n");
      out.write("\t               <div class=\"mail-options-group\">\r\n");
      out.write("\t                   <div class=\"adomx-dropdown\">\r\n");
      out.write("\t                       <button class=\"mail-button-filter toggle\"><i class=\"zmdi zmdi-filter-list\"></i></button>\r\n");
      out.write("\t                       <ul class=\"adomx-dropdown-menu\">\r\n");
      out.write("\t                           <li><a href=\"#\">All</a></li>\r\n");
      out.write("\t                           <li><a href=\"#\">None</a></li>\r\n");
      out.write("\t                           <li><a href=\"#\">Read</a></li>\r\n");
      out.write("\t                           <li><a href=\"#\">Unread</a></li>\r\n");
      out.write("\t                           <li><a href=\"#\">Starred</a></li>\r\n");
      out.write("\t                           <li><a href=\"#\">Unstarred</a></li>\r\n");
      out.write("\t                       </ul>\r\n");
      out.write("\t                   </div>\r\n");
      out.write("\t                   <button class=\"mail-button-reply\"><i class=\"zmdi zmdi-mail-reply\"></i></button>\r\n");
      out.write("\t                   <button class=\"mail-button-refresh\"><i class=\"zmdi zmdi-replay\"></i></button>\r\n");
      out.write("\t               </div>\r\n");
      out.write("\t\r\n");
      out.write("\t               <div class=\"mail-options-group\">\r\n");
      out.write("\t                   <button class=\"mail-button-starred\"><i class=\"zmdi zmdi-star-outline\"></i></button>\r\n");
      out.write("\t                   <button class=\"mail-button-archive\"><i class=\"zmdi zmdi-archive\"></i></button>\r\n");
      out.write("\t                   <div class=\"adomx-dropdown\">\r\n");
      out.write("\t                       <button class=\"mail-button-category toggle\"><i class=\"zmdi zmdi-folder\"></i></button>\r\n");
      out.write("\t                       <ul class=\"adomx-dropdown-menu\">\r\n");
      out.write("\t                           <li><span>Move to:</span></li>\r\n");
      out.write("\t                           <li>\r\n");
      out.write("\t                               <hr>\r\n");
      out.write("\t                           </li>\r\n");
      out.write("\t                           <li class=\"checked\"><a href=\"#\"><i class=\"check\"></i> Forwarded</a></li>\r\n");
      out.write("\t                           <li><a href=\"#\"><i class=\"check\"></i> Replied</a></li>\r\n");
      out.write("\t                           <li><a href=\"#\"><i class=\"check\"></i> Social</a></li>\r\n");
      out.write("\t                           <li><a href=\"#\"><i class=\"check\"></i> Forums</a></li>\r\n");
      out.write("\t                           <li><a href=\"#\"><i class=\"check\"></i> Promotions</a></li>\r\n");
      out.write("\t                           <li>\r\n");
      out.write("\t                               <hr>\r\n");
      out.write("\t                           </li>\r\n");
      out.write("\t                           <li><a href=\"#\">Spam</a></li>\r\n");
      out.write("\t                           <li><a href=\"#\">Trash</a></li>\r\n");
      out.write("\t                           <li>\r\n");
      out.write("\t                               <hr>\r\n");
      out.write("\t                           </li>\r\n");
      out.write("\t                           <li><a href=\"#\">Create New</a></li>\r\n");
      out.write("\t                           <li><a href=\"#\">Manage Folder</a></li>\r\n");
      out.write("\t                       </ul>\r\n");
      out.write("\t                   </div>\r\n");
      out.write("\t               </div>\r\n");
      out.write("\t\r\n");
      out.write("\t               <div class=\"mail-options-group\">\r\n");
      out.write("\t                   <button class=\"mail-button-delete\"><i class=\"zmdi zmdi-delete\"></i></button>\r\n");
      out.write("\t                   <div class=\"adomx-dropdown\">\r\n");
      out.write("\t                       <button class=\"mail-button-snooze toggle\"><i class=\"zmdi zmdi-alarm-snooze\"></i></button>\r\n");
      out.write("\t                       <ul class=\"adomx-dropdown-menu\">\r\n");
      out.write("\t                           <li><span>Snooze ultil..</span></li>\r\n");
      out.write("\t                           <li class=\"checked\"><a href=\"#\">Later today <span class=\"ml-auto\">6:00 PM</span></a></li>\r\n");
      out.write("\t                           <li class=\"checked\"><a href=\"#\">Tomorrow <span class=\"ml-auto\">8:00 AM</span></a></li>\r\n");
      out.write("\t                           <li class=\"checked\"><a href=\"#\">Next week <span class=\"ml-auto\">8:00 AM</span></a></li>\r\n");
      out.write("\t                           <li class=\"checked\"><a href=\"#\">Next weekend <span class=\"ml-auto\">8:00 AM</span></a></li>\r\n");
      out.write("\t                           <li>\r\n");
      out.write("\t                               <hr>\r\n");
      out.write("\t                           </li>\r\n");
      out.write("\t                           <li><a href=\"#\"><i class=\"zmdi zmdi-calendar\"></i> Pick date & time</a></li>\r\n");
      out.write("\t                       </ul>\r\n");
      out.write("\t                   </div>\r\n");
      out.write("\t                   <div class=\"adomx-dropdown\">\r\n");
      out.write("\t                       <button class=\"mail-button-label toggle\"><i class=\"zmdi zmdi-label\"></i></button>\r\n");
      out.write("\t                       <ul class=\"adomx-dropdown-menu\">\r\n");
      out.write("\t                           <li><span>Label as:</span></li>\r\n");
      out.write("\t                           <li>\r\n");
      out.write("\t                               <hr>\r\n");
      out.write("\t                           </li>\r\n");
      out.write("\t                           <li class=\"checked\"><a href=\"#\"><i class=\"check\"></i> Forwarded</a></li>\r\n");
      out.write("\t                           <li><a href=\"#\"><i class=\"check\"></i> Replied</a></li>\r\n");
      out.write("\t                           <li><a href=\"#\"><i class=\"check\"></i> Social</a></li>\r\n");
      out.write("\t                           <li><a href=\"#\"><i class=\"check\"></i> Forums</a></li>\r\n");
      out.write("\t                           <li><a href=\"#\"><i class=\"check\"></i> Promotions</a></li>\r\n");
      out.write("\t                           <li>\r\n");
      out.write("\t                               <hr>\r\n");
      out.write("\t                           </li>\r\n");
      out.write("\t                           <li><a href=\"#\">Create New</a></li>\r\n");
      out.write("\t                           <li><a href=\"#\">Manage Labels</a></li>\r\n");
      out.write("\t                       </ul>\r\n");
      out.write("\t                   </div>\r\n");
      out.write("\t                   <div class=\"adomx-dropdown\">\r\n");
      out.write("\t                       <button class=\"mail-button-more toggle\"><i class=\"zmdi zmdi-more-vert\"></i></button>\r\n");
      out.write("\t                       <ul class=\"adomx-dropdown-menu adomx-dropdown-menu-right\">\r\n");
      out.write("\t                           <li><a href=\"#\">Mark all as read</a></li>\r\n");
      out.write("\t                           <li><a href=\"#\">Mark as read</a></li>\r\n");
      out.write("\t                           <li><a href=\"#\">Mark as unread</a></li>\r\n");
      out.write("\t                           <li><a href=\"#\">Mark as inportant</a></li>\r\n");
      out.write("\t                           <li><a href=\"#\">Mark as not inportant</a></li>\r\n");
      out.write("\t                           <li><a href=\"#\">Add to Tasks</a></li>\r\n");
      out.write("\t                           <li><a href=\"#\">Add Star</a></li>\r\n");
      out.write("\t                           <li><a href=\"#\">Filter messages like these</a></li>\r\n");
      out.write("\t                           <li><a href=\"#\">Mute</a></li>\r\n");
      out.write("\t                       </ul>\r\n");
      out.write("\t                   </div>\r\n");
      out.write("\t               </div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t           </div>\r\n");
      out.write("\t           <!--Mail Options End-->");
      out.write("<!-- 수신 메시지 삭제 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--Mail List Start-->\r\n");
      out.write("<div class=\"mail-list\">\r\n");
      out.write("\r\n");
      //  c:forEach
      org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
      boolean _jspx_th_c_005fforEach_005f0_reused = false;
      try {
        _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
        _jspx_th_c_005fforEach_005f0.setParent(null);
        // /WEB-INF/views/message/deleteMessageBox.jsp(16,0) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
        _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/message/deleteMessageBox.jsp(16,0) '${messageList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${messageList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
        // /WEB-INF/views/message/deleteMessageBox.jsp(16,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fforEach_005f0.setVar("message");
        int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
        try {
          int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
          if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
            do {
              //  c:if
              org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
              boolean _jspx_th_c_005fif_005f0_reused = false;
              try {
                _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
                _jspx_th_c_005fif_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
                // /WEB-INF/views/message/deleteMessageBox.jsp(17,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message.message_sender_delete==1}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
                int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
                if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                  do {
                    //  c:if
                    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
                    boolean _jspx_th_c_005fif_005f1_reused = false;
                    try {
                      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
                      _jspx_th_c_005fif_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
                      // /WEB-INF/views/message/deleteMessageBox.jsp(18,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message.message_sender eq loginUser.member_id }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
                      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
                      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                        do {
                          out.write("<!--Mail Start-->\r\n");
                          out.write("<div class=\"mail\">\r\n");
                          out.write("\r\n");
                          out.write("    <div class=\"left\">\r\n");
                          out.write("        <label class=\"adomx-checkbox\"><input type=\"checkbox\"> <i class=\"icon\"></i></label>\r\n");
                          out.write("        <button class=\"mail-button-starred\"><i class=\"zmdi zmdi-star-outline\"></i></button>\r\n");
                          out.write("    </div>\r\n");
                          out.write("\r\n");
                          out.write("    <div class=\"middle\">\r\n");
                          out.write("\r\n");
                          out.write("        <div class=\"top\">\r\n");
                          out.write("            <h4 class=\"name\"><a href=\"");
                          out.print(request.getContextPath());
                          out.write("/message/detail.page?message_no=");
                          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message.message_no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
                          out.write('"');
                          out.write('>');
                          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message.message_sender}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
                          out.write("</a></h4>\r\n");
                          out.write("            <span class=\"date\">");
                          if (_jspx_meth_fmt_005fformatDate_005f0(_jspx_th_c_005fif_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
                            return;
                          out.write("</span>\r\n");
                          out.write("        </div>\r\n");
                          out.write("\r\n");
                          out.write("        <div class=\"body\">\r\n");
                          out.write("            <p>");
                          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message.message_title }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
                          out.write("</p>\r\n");
                          out.write("        </div>\r\n");
                          out.write("\r\n");
                          out.write("    </div>\r\n");
                          out.write("\r\n");
                          out.write("    <div class=\"right\">\r\n");
                          out.write("        <button class=\"mail-button-delete\"><i class=\"zmdi zmdi-delete\"></i></button>\r\n");
                          out.write("        <div class=\"adomx-dropdown\">\r\n");
                          out.write("            <button class=\"mail-button-option toggle\"><i class=\"zmdi zmdi-more-vert\"></i></button>\r\n");
                          out.write("            <ul class=\"adomx-dropdown-menu adomx-dropdown-menu-right\">\r\n");
                          out.write("                <li><a href=\"#\">Action</a></li>\r\n");
                          out.write("                <li><a href=\"#\">Another Action</a></li>\r\n");
                          out.write("                <li><a href=\"#\">Something else</a></li>\r\n");
                          out.write("            </ul>\r\n");
                          out.write("        </div>\r\n");
                          out.write("    </div>\r\n");
                          out.write("\r\n");
                          out.write("</div>\r\n");
                          out.write("<!--Mail End-->\r\n");
                          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
                          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                            break;
                        } while (true);
                      }
                      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                        return;
                      }
                      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
                      _jspx_th_c_005fif_005f1_reused = true;
                    } finally {
                      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
                    }
                    int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
                    if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                      break;
                  } while (true);
                }
                if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                  return;
                }
                _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
                _jspx_th_c_005fif_005f0_reused = true;
              } finally {
                org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
              }
              out.write("<!-- 발신 메시지 삭제 -->\r\n");
              out.write("\r\n");
              //  c:if
              org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
              boolean _jspx_th_c_005fif_005f2_reused = false;
              try {
                _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
                _jspx_th_c_005fif_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
                // /WEB-INF/views/message/deleteMessageBox.jsp(60,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message.message_receiver_delete==1}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
                int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
                if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                  do {
                    //  c:if
                    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
                    boolean _jspx_th_c_005fif_005f3_reused = false;
                    try {
                      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
                      _jspx_th_c_005fif_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f2);
                      // /WEB-INF/views/message/deleteMessageBox.jsp(61,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message.message_receiver eq loginUser.member_id }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
                      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
                      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                        do {
                          out.write("<!--Mail Start-->\r\n");
                          out.write("<div class=\"mail\">\r\n");
                          out.write("\r\n");
                          out.write("    <div class=\"left\">\r\n");
                          out.write("        <label class=\"adomx-checkbox\"><input type=\"checkbox\"> <i class=\"icon\"></i></label>\r\n");
                          out.write("        <button class=\"mail-button-starred\"><i class=\"zmdi zmdi-star-outline\"></i></button>\r\n");
                          out.write("    </div>\r\n");
                          out.write("\r\n");
                          out.write("    <div class=\"middle\">\r\n");
                          out.write("\r\n");
                          out.write("        <div class=\"top\">\r\n");
                          out.write("            <h4 class=\"name\"><a href=\"");
                          out.print(request.getContextPath());
                          out.write("/message/detail.page?message_no=");
                          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message.message_no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
                          out.write('"');
                          out.write('>');
                          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message.message_sender}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
                          out.write("</a></h4>\r\n");
                          out.write("            <span class=\"date\">");
                          if (_jspx_meth_fmt_005fformatDate_005f1(_jspx_th_c_005fif_005f3, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
                            return;
                          out.write("</span>\r\n");
                          out.write("        </div>\r\n");
                          out.write("\r\n");
                          out.write("        <div class=\"body\">\r\n");
                          out.write("            <p>");
                          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message.message_title }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
                          out.write("</p>\r\n");
                          out.write("        </div>\r\n");
                          out.write("\r\n");
                          out.write("    </div>\r\n");
                          out.write("\r\n");
                          out.write("    <div class=\"right\">\r\n");
                          out.write("        <button class=\"mail-button-delete\"><i class=\"zmdi zmdi-delete\"></i></button>\r\n");
                          out.write("        <div class=\"adomx-dropdown\">\r\n");
                          out.write("            <button class=\"mail-button-option toggle\"><i class=\"zmdi zmdi-more-vert\"></i></button>\r\n");
                          out.write("            <ul class=\"adomx-dropdown-menu adomx-dropdown-menu-right\">\r\n");
                          out.write("                <li><a href=\"#\">Action</a></li>\r\n");
                          out.write("                <li><a href=\"#\">Another Action</a></li>\r\n");
                          out.write("                <li><a href=\"#\">Something else</a></li>\r\n");
                          out.write("            </ul>\r\n");
                          out.write("        </div>\r\n");
                          out.write("    </div>\r\n");
                          out.write("\r\n");
                          out.write("</div>\r\n");
                          out.write("<!--Mail End-->\r\n");
                          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
                          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                            break;
                        } while (true);
                      }
                      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                        return;
                      }
                      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
                      _jspx_th_c_005fif_005f3_reused = true;
                    } finally {
                      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
                    }
                    int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
                    if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                      break;
                  } while (true);
                }
                if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                  return;
                }
                _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
                _jspx_th_c_005fif_005f2_reused = true;
              } finally {
                org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
              }
              int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                break;
            } while (true);
          }
          if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
            return;
          }
        } catch (java.lang.Throwable _jspx_exception) {
          while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
            out = _jspx_page_context.popBody();
          _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
        } finally {
          _jspx_th_c_005fforEach_005f0.doFinally();
        }
        _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
        _jspx_th_c_005fforEach_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
      }
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t               \r\n");
      out.write("\t               \r\n");
      out.write("</div>\r\n");
      out.write("\t           <!--Mail List End-->\r\n");
      out.write("\t\r\n");
      out.write("\t       </div>\r\n");
      out.write("\t       <!--Mail List Container End-->\r\n");
      out.write("\t\r\n");
      out.write("\t   </div>\r\n");
      out.write("\t   <!--Mail Wrapper Start-->\r\n");
      out.write("\t\r\n");
      out.write("\t   <!-- Modal -->\r\n");
      out.write("\t           <div class=\"compose-mail-modal modal fade\" id=\"modal-compose-mail\">\r\n");
      out.write("\t               <div class=\"modal-dialog modal-dialog-centered modal-xl\">\r\n");
      out.write("\t                   <div class=\"modal-content\">\r\n");
      out.write("\t\r\n");
      out.write("\t                       <div class=\"modal-header\">\r\n");
      out.write("\t                           <h5 class=\"modal-title\">새 메시지 작성</h5>\r\n");
      out.write("\t                           <button type=\"button\" class=\"close\" data-dismiss=\"modal\"><i class=\"zmdi zmdi-close\"></i></button>\r\n");
      out.write("\t                       </div>\r\n");
      out.write("\t\r\n");
      out.write("\t                       <div class=\"form\">\r\n");
      out.write("\t                           <form role=\"form\" action=\"regist.do\" name=\"registForm\" method=\"post\">\r\n");
      out.write("\t                               <div class=\"row\">\r\n");
      out.write("\t                                   <div class=\"col-12 mb-30\">\r\n");
      out.write("\t                                       <input class=\"form-control\" type=\"email\"  id=\"message_receiver\" name=\"message_sender\" placeholder=\"발신자\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.member_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t                                   </div>\r\n");
      out.write("\t                                   <div class=\"col-12 mb-30\">\r\n");
      out.write("\t                                       <input class=\"form-control\" type=\"email\"  id=\"message_receiver\" name=\"message_receiver\" placeholder=\"수신자\">\r\n");
      out.write("\t                                   </div>\r\n");
      out.write("\t                                   <div class=\"col-12 mb-30\">\r\n");
      out.write("\t                                       <input class=\"form-control\" type=\"email\"   id=\"message_title\"  name=\"message_title\"  placeholder=\"제목\">\r\n");
      out.write("\t                                   </div>\r\n");
      out.write("\t                                   <div class=\"col-12 mb-30\">\r\n");
      out.write("\t                                       <textarea class=\"summernote\" id=\"message_content\" name=\"message_content\"></textarea>\r\n");
      out.write("\t                                   </div>\r\n");
      out.write("\t                                   <div class=\"buttons-group col-12\">\r\n");
      out.write("\t                                       <button type=\"button\" class=\"button button-outline button-round button-warning\"><i class=\"zmdi zmdi-attachment-alt\"></i> 파일첨부</button>\r\n");
      out.write("\t                                       <button type=\"button\" class=\"button button-round button-primary\" id=\"registBtn\">전송</button>\r\n");
      out.write("\t                                   </div>\r\n");
      out.write("\t\r\n");
      out.write("\t                               </div>\r\n");
      out.write("\t                           </form>\r\n");
      out.write("\t                       </div>\r\n");
      out.write("\t\r\n");
      out.write("\t                   </div>\r\n");
      out.write("\t               </div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<script>\r\n");
      out.write("\t$('#registBtn').on('click', function(e) {\r\n");
      out.write("\t\t//alert(\"regist click\");\r\n");
      out.write("\t\tvar form = document.registForm;\r\n");
      out.write("\r\n");
      out.write("\t\tif(form.message_title.value==\"\"){\r\n");
      out.write("\t\t\talert(\"제목은 필수입니다.\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tform.submit();\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t</script>");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_fmt_005fformatDate_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatDate
    org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag _jspx_th_fmt_005fformatDate_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag) _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag.class);
    boolean _jspx_th_fmt_005fformatDate_005f0_reused = false;
    try {
      _jspx_th_fmt_005fformatDate_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatDate_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /WEB-INF/views/message/deleteMessageBox.jsp(31,31) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f0.setValue((java.util.Date) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message.message_send_date}", java.util.Date.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/views/message/deleteMessageBox.jsp(31,31) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f0.setPattern("yyyy-MM-dd");
      int _jspx_eval_fmt_005fformatDate_005f0 = _jspx_th_fmt_005fformatDate_005f0.doStartTag();
      if (_jspx_th_fmt_005fformatDate_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatDate_005f0);
      _jspx_th_fmt_005fformatDate_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatDate_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatDate_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatDate_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f3, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatDate
    org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag _jspx_th_fmt_005fformatDate_005f1 = (org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag) _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag.class);
    boolean _jspx_th_fmt_005fformatDate_005f1_reused = false;
    try {
      _jspx_th_fmt_005fformatDate_005f1.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatDate_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f3);
      // /WEB-INF/views/message/deleteMessageBox.jsp(74,31) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f1.setValue((java.util.Date) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message.message_send_date}", java.util.Date.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/views/message/deleteMessageBox.jsp(74,31) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f1.setPattern("yyyy-MM-dd");
      int _jspx_eval_fmt_005fformatDate_005f1 = _jspx_th_fmt_005fformatDate_005f1.doStartTag();
      if (_jspx_th_fmt_005fformatDate_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatDate_005f1);
      _jspx_th_fmt_005fformatDate_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatDate_005f1, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatDate_005f1_reused);
    }
    return false;
  }
}
