/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.57
 * Generated at: 2020-12-04 17:05:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board.pds;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class pdsDetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/C:/soo/A_TeachingMaterial/7.LastProject/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ddit/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1602513789311L));
    _jspx_dependants.put("jar:file:/C:/soo/A_TeachingMaterial/7.LastProject/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ddit/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/board/pds/reply_js.jsp", Long.valueOf(1606857367452L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<div class=\"content-body\">\r\n");
      out.write("\t<div class=\"add-edit-product-wrap col-12\" style=\"background-color: white; margin-top:-50px \">\r\n");
      out.write("\t\t<!-- Page Headings Start -->\r\n");
      out.write("\t\t<div class=\"row justify-content-between align-items-center mb-10\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t<!-- Page Heading Start -->\r\n");
      out.write("\t\t\t<div class=\"col-12 col-lg-auto mb-20\">\r\n");
      out.write("\t\t\t\t<div class=\"page-heading\">\r\n");
      out.write("\t\t\t\t\t<h3 class=\"title\" style=\"text-align: left;\">학습자료실</h3>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- Page Heading End -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- Page Headings End -->\r\n");
      out.write("\t\r\n");
      out.write("\t\t<!-- improvement and suggestions 제목 -->\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-12\">\r\n");
      out.write("\t\t\t\t<div class=\"box\" style=\"border:1px solid #F0F0F0\">\r\n");
      out.write("\t\t\t\t\t<div class=\"box-head\" style=\"display: inline-block; margin: 0 auto; \">\r\n");
      out.write("\t\t\t\t\t\t<h3 class=\"title\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${post.post_title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h3>\r\n");
      out.write("\t\t\t\t\t\t<a>작성자 : </a> <a>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${post.post_writer}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</a> &nbsp;&nbsp; <a>|</a> <a>\r\n");
      out.write("\t\t\t\t\t\t\t작성일자 : </a> <a>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${post.post_reg_date}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</a> &nbsp;&nbsp; <a>|</a> <a>\r\n");
      out.write("\t\t\t\t\t\t\t수정일자 : </a> <a>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${post.post_update_date}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</a> &nbsp;&nbsp; <a>|</a> <a>\r\n");
      out.write("\t\t\t\t\t\t\t조회수 : </a> <a>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${post.post_viewcnt }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div style=\"z-index: 1; position: absolute; bottom: 20px; right: 40px; margin-top: 20px;\">\r\n");
      out.write("\t\t\t\t\t\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("<button class=\"btn btn-outline\" style=\"border:1px solid #dddddd;\" id=\"listBtn\">\r\n");
      out.write("\t\t\t\t\t\t\t<span>목록</span>\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- improvement and suggestions 제목 END -->\r\n");
      out.write("\t\t<div class=\"attachment\" style=\"border:1px solid #F0F0F0; background:#FAFAFA;\">\r\n");
      out.write("\t\t\t<div style=\"margin-left:20px;\">\r\n");
      out.write("\t\t\t\t<h5 class=\"title\">첨부파일</h5>\r\n");
      out.write("\t\t\t\t");
      //  c:if
      org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
      boolean _jspx_th_c_005fif_005f1_reused = false;
      try {
        _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
        _jspx_th_c_005fif_005f1.setParent(null);
        // /WEB-INF/views/board/pds/pdsDetail.jsp(52,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!empty post.attachList }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
        int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
        if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            //  c:forEach
            org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
            boolean _jspx_th_c_005fforEach_005f0_reused = false;
            try {
              _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
              _jspx_th_c_005fforEach_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
              // /WEB-INF/views/board/pds/pdsDetail.jsp(53,5) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
              _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/board/pds/pdsDetail.jsp(53,5) '${post.attachList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${post.attachList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
              // /WEB-INF/views/board/pds/pdsDetail.jsp(53,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_c_005fforEach_005f0.setVar("attach");
              // /WEB-INF/views/board/pds/pdsDetail.jsp(53,5) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_c_005fforEach_005f0.setVarStatus("c");
              int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
              try {
                int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
                if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                  do {
                    out.write("<div class=\"row\" style=\"cursor: pointer; margin-left:3px; margin-bottom:5px;\" \r\n");
                    out.write("\t\t\t\t\t\t\tonclick=\"location.href='");
                    out.print(request.getContextPath());
                    out.write("/board/attach/getFile.do?post_no=");
                    out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${post.post_no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
                    out.write("&attach_no=");
                    out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${attach.attach_no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
                    out.write("';\">\r\n");
                    out.write("\t\t\t\t\t\t\t<span class=\"fa fa-download\">");
                    out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${attach.attach_original_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
                    out.write("</span>\r\n");
                    out.write("\t\t\t\t\t\t</div>\r\n");
                    out.write("\t\t\t\t\t");
                    int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
                    if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                      break;
                  } while (true);
                }
                if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                  return;
                }
              } catch (java.lang.Throwable _jspx_exception) {
                while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
                  out = _jspx_page_context.popBody();
                _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
              } finally {
                _jspx_th_c_005fforEach_005f0.doFinally();
              }
              _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
              _jspx_th_c_005fforEach_005f0_reused = true;
            } finally {
              org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
            }
            int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
        _jspx_th_c_005fif_005f1_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
      }
      out.write("</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\t<!-- improvement and suggestions 내용 -->\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-12\">\r\n");
      out.write("\t\t\t\t<div class=\"box\">\r\n");
      out.write("\t\t\t\t\t<div class=\"box-body\" style=\"background-color: white;\">\r\n");
      out.write("\t\t\t\t\t\t<h5>내용</h5>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"content\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${post.post_content}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- improvement and suggestions 내용 END -->\r\n");
      out.write("\t\t<!-- 댓글 -->\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-12\">\r\n");
      out.write("\t\t\t\t<div class=\"box\">\r\n");
      out.write("\t\t\t\t\t<div class=\"timeline\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"\" id=\"repliesDiv\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"replyLi\" data-reply_no={{reply_no}}></div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" id=\"newreply_writer\" name=\"newreply_writer\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" id=\"newreply_no\" name=\"newreply_no\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"text-center\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul id=\"pagination\" class=\"pagination justify-content-center m-0\"></ul>\r\n");
      out.write("\t\t\t\t\t\t</div> \r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- 댓글 END -->\r\n");
      out.write("\t\t<!-- Modal -->\r\n");
      out.write("\t\t<div class=\"modal fade\" id=\"exampleModal5\">\r\n");
      out.write("\t\t\t<div class=\"modal-dialog modal-dialog-centered\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t\t<h4 class=\"modal-title\"></h4>\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\">\r\n");
      out.write("\t\t\t\t\t\t\t<span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-body\" data-reply_no>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"reply_content\" style=\"text-align:left; margin: 0 auto;\" maxlength=\"300\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t\t<button class=\"button button-info\" data-dismiss=\"modal\">닫기</button>\r\n");
      out.write("\t\t\t\t\t\t<button class=\"button button-primary\" data-dismiss=\"modal\" id=\"replyModBtn\">수정</button>\r\n");
      out.write("\t\t\t\t\t\t<button class=\"button button-danger\" data-dismiss=\"modal\" id=\"replyDelBtn\">삭제</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- modalEND -->\r\n");
      out.write("\t</div>\t\r\n");
      out.write("</div>\r\n");
      out.write("<!-- content-body END -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<form role=\"form\">\r\n");
      out.write("\t<input type=\"hidden\" name=\"post_no\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${post.post_no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\t$('#newreply_content').keyup(function() {\r\n");
      out.write("\t\tif ($(this).val().length > $(this).attr('maxlength')) {\r\n");
      out.write("\t\t\t$(this).val($(this).val().substr(0, $(this).attr('maxlength')));\r\n");
      out.write("\t\t\talert('글자수 제한을 초과하였습니다. 댓글은 300자 이내로 작성 가능합니다.');\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\tvar formObj = $(\"form[role='form']\");\r\n");
      out.write("\r\n");
      out.write("\t$('#modifyBtn').on('click', function(event) {\r\n");
      out.write("\t\tformObj.attr({\r\n");
      out.write("\t\t\t'action' : 'modifyForm.do',\r\n");
      out.write("\t\t\t'method' : 'post'\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tformObj.submit();\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t$(\"#removeBtn\").on(\"click\", function() {\r\n");
      out.write("\t\tvar chk = confirm(\"정말 삭제하시겠습니까?\");\r\n");
      out.write("\t\tif (chk) {\r\n");
      out.write("\t\t\tformObj.attr({\r\n");
      out.write("\t\t\t\t'action' : 'remove.do',\r\n");
      out.write("\t\t\t\t'method' : 'post'\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tformObj.submit();\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t$(\"#listBtn\").on(\"click\", function() {\r\n");
      out.write("\t\tlocation.href=\"");
      out.print(request.getContextPath());
      out.write("/board/pds/list.do?board=pds&board_no=BOARD005\";\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/4.7.6/handlebars.min.js\"></script>\r\n");
      out.write("<script type=\"text/x-handlebars-template\" id=\"reply-list-template\" >\r\n");
      out.write("\r\n");
      out.write("{{#each .}}\r\n");
      out.write("<div class=\"replyLi\">\r\n");
      out.write("\t<div class=\"details\">\r\n");
      out.write("\t\t<hr>\r\n");
      out.write("\t\t<input type=\"hidden\" class=\"modal_reply_writer\" name=\"reply_writer\" value={{reply_writer}}>\t\r\n");
      out.write("\t\t<input type=\"hidden\" class=\"modal_reply_no\" name=\"reply_no\" value={{reply_no}}>\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<h5 class=\"title\">{{reply_writer}}</h5>\r\n");
      out.write("\t\t<div class=\"content\">\r\n");
      out.write("\t\t\t<div id=\"{{reply_no}}-reply_content\" style=\"display: inline-block;\">\r\n");
      out.write("\t\t\t\t{{reply_content}}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div style=\"display: inline-block;style=;float: right;\">\r\n");
      out.write("               {{{reply_writerChe reply_writer reply_no}}}\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("{{/each}}\t\r\n");
      out.write("</script>   \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script> //댓글 리스트\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\t\r\n");
      out.write("\tHandlebars.registerHelper(\"reply_writerChe\", function(reply_writer, reply_no){\r\n");
      out.write("\t\tvar memberId = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.member_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(reply_writer == memberId){\r\n");
      out.write("\t\t\treturn '<i class=\"zmdi zmdi-edit\" id=\"modifyReplyBtn\" data-toggle=\"modal\" data-reply_no='+reply_no+' data-reply_writer='+reply_writer+' data-target=\"#exampleModal5\">수정</i>'\r\n");
      out.write("\t\t }else{\r\n");
      out.write("\t\t\treturn \"\"\r\n");
      out.write("\t\t} \r\n");
      out.write("\t}); \r\n");
      out.write("\t\r\n");
      out.write("\tHandlebars.registerHelper(\"prettifyDate\",function(timeValue){\r\n");
      out.write("\t\tvar dateObj=new Date(timeValue);\r\n");
      out.write("\t\tvar year=dateObj.getFullYear();\r\n");
      out.write("\t\tvar month=dateObj.getMonth()+1;\r\n");
      out.write("\t\tvar date=dateObj.getDate();\r\n");
      out.write("\t\treturn year+\"/\"+month+\"/\"+date;\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("var replyPage=1;\r\n");
      out.write("var realEndPage=1;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("getPage(\"");
      out.print(request.getContextPath());
      out.write("/replies/board/pds/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${post.post_no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\"+replyPage);\r\n");
      out.write("\r\n");
      out.write("//reply list\r\n");
      out.write("function getPage(pageInfo){    \r\n");
      out.write("   $.getJSON(pageInfo,function(data){   \r\n");
      out.write("      printData(data.replyList,$('#repliesDiv'),$('#reply-list-template'));\r\n");
      out.write("      printPaging(data.pageMaker,$('.pagination'));   \r\n");
      out.write("      if(data.pageMaker.realEndPage>0){\r\n");
      out.write("         realEndPage=data.pageMaker.realEndPage;\r\n");
      out.write("      }\r\n");
      out.write("   });\r\n");
      out.write("      $('.replyLi').remove();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("var printData=function(replyArr,target,templateObject){\r\n");
      out.write("   var template=Handlebars.compile(templateObject.html());\r\n");
      out.write("   var html = template(replyArr);   \r\n");
      out.write("   $('.replyLi').remove();\r\n");
      out.write("   target.after(html);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//reply pagination\r\n");
      out.write("var printPaging=function(pageMaker,target){\r\n");
      out.write("   var str=\"\";\r\n");
      out.write("   \r\n");
      out.write("   if(pageMaker.prev){\r\n");
      out.write("      str+=\"<li class='page-item'><a class='page-link' href='\"+(pageMaker.startPage-1)+\"'> <i class='fas fa-angle-left'/> </a></li>\";         \r\n");
      out.write("   }\r\n");
      out.write("   for(var i=pageMaker.startPage;i<=pageMaker.endPage;i++){\r\n");
      out.write("      var strClass = pageMaker.cri.page == i ? 'active' : '';\r\n");
      out.write("      str+=\"<li class='page-item \"+strClass+\"'><a class='page-link' href='\"+i+\"'>\"+i+\"</a></li>\";\r\n");
      out.write("   }\r\n");
      out.write("   if(pageMaker.next){\r\n");
      out.write("      str+=\"<li class='page-item' ><a class='page-link' href='\"+(pageMaker.endPage+1)+\"'> <i class='fas fa-angle-right'/> </a></li>\";\r\n");
      out.write("   }\r\n");
      out.write("   target.html(str);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("$('.pagination').on('click','li a',function(event){\r\n");
      out.write("   event.preventDefault();\r\n");
      out.write("   replyPage=$(this).attr(\"href\");\r\n");
      out.write("   getPage(\"");
      out.print(request.getContextPath());
      out.write("/replies/board/pds/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${post.post_no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\"+replyPage);\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("//reply modify 권한체크\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("$('div.timeline').on('click','#modifyReplyBtn',function(event){   \r\n");
      out.write("   var reply_no = $(this).attr(\"data-reply_no\");\r\n");
      out.write("   var reply_writer = $(this).attr(\"data-reply_writer\");\r\n");
      out.write("   var reply_content = $('#'+reply_no+'-reply_content').text();\r\n");
      out.write("      \r\n");
      out.write("   if(reply_writer!=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.member_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"){\r\n");
      out.write("      alert(\"수정 권한이 없습니다.\");\r\n");
      out.write("      $(this).attr(\"data-toggle\",\"\");\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   $('#reply_content').val(reply_content);\r\n");
      out.write("   $('.modal-title').text(reply_no);\r\n");
      out.write("      \r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("$('#replyAddBtn').on('click',function(e){\r\n");
      out.write("\r\n");
      out.write("\t   var reply_writer=$('#newreply_writer').val();\r\n");
      out.write("\t   var reply_content=$('#newreply_content').val();\r\n");
      out.write("\t   \r\n");
      out.write("\t   if(reply_content==\"\"){\r\n");
      out.write("\t      alert('댓글 내용은 필수입니다.');\r\n");
      out.write("\t      $('#newreply_content').focus().css(\"border-color\",\"red\")\r\n");
      out.write("\t      .attr(\"placeholder\",\"내용은 필수입니다.\");         \r\n");
      out.write("\t      return;\r\n");
      out.write("\t   }\r\n");
      out.write("\t   \r\n");
      out.write("\t   var data={\r\n");
      out.write("\t         \"post_no\":\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${post.post_no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\",\r\n");
      out.write("\t         \"reply_writer\":\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.member_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\",\r\n");
      out.write("\t         \"reply_content\":reply_content   \r\n");
      out.write("\t   }\r\n");
      out.write("\t   \r\n");
      out.write("\t   \r\n");
      out.write("\t   $.ajax({\r\n");
      out.write("\t      url:\"");
      out.print(request.getContextPath());
      out.write("/replies\",\r\n");
      out.write("\t      type:\"post\",\r\n");
      out.write("\t      data:JSON.stringify(data),   \r\n");
      out.write("\t      contentType:\"application/json\", //보내는 data 형식 지정\r\n");
      out.write("\t      dataType:\"text\", //받는 data 형식 지정\r\n");
      out.write("\t      success:function(data){\r\n");
      out.write("\t         var result=data.split(',');\r\n");
      out.write("\t         if(result[0]==\"SUCCESS\"){\r\n");
      out.write("\t            alert('댓글이 등록되었습니다.');\r\n");
      out.write("\t            getPage(\"");
      out.print(request.getContextPath());
      out.write("/replies/board/pds/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${post.post_no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\"+result[1]);\r\n");
      out.write("\t            $('#newreply_content').val(\"\");\r\n");
      out.write("\t            $('.replyLi').remove();\r\n");
      out.write("\t         }else{\r\n");
      out.write("\t            alert('댓글이 등록을 실패했습니다.');   \r\n");
      out.write("\t         }\r\n");
      out.write("\t      }\r\n");
      out.write("\t   });\r\n");
      out.write("\t   \r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("$('#replyModBtn').on('click',function(event){\r\n");
      out.write("    var reply_no=$('.modal-title').text();\r\n");
      out.write("   var reply_content=$('#reply_content').val();\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("   var sendData={\r\n");
      out.write("         reply_no:reply_no,\r\n");
      out.write("         reply_content:reply_content\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   $.ajax({\r\n");
      out.write("      url:\"");
      out.print(request.getContextPath());
      out.write("/replies/board/pds/\"+reply_no,\r\n");
      out.write("      type:\"put\",\r\n");
      out.write("      data:JSON.stringify(sendData),\r\n");
      out.write("      headers:{\r\n");
      out.write("         \"Content-Type\":\"application/json\",\r\n");
      out.write("         \"X-HTTP-Method-Override\":\"PUT\"\r\n");
      out.write("      },\r\n");
      out.write("      success:function(result){\r\n");
      out.write("         alert(\"수정되었습니다.\");         \r\n");
      out.write("      },\r\n");
      out.write("      error:function(error){\r\n");
      out.write("         alert('수정 실패했습니다.');      \r\n");
      out.write("      },\r\n");
      out.write("      complete:function(){\r\n");
      out.write("          $('#exampleModal5').modal('hide');\r\n");
      out.write("         $('.replyLi').remove();\r\n");
      out.write("         getPage(\"");
      out.print(request.getContextPath());
      out.write("/replies/board/pds/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${post.post_no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\"+replyPage);\r\n");
      out.write("      }\r\n");
      out.write("   });\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("$('#replyDelBtn').on('click',function(event){\r\n");
      out.write("   \r\n");
      out.write("   var reply_no=$('.modal-title').text();\r\n");
      out.write("   \r\n");
      out.write("   var sendData={\r\n");
      out.write("         post_no:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${post.post_no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\",\r\n");
      out.write("         reply_no:reply_no,\r\n");
      out.write("         page:replyPage\r\n");
      out.write("   };\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   $.ajax({\r\n");
      out.write("      url:\"");
      out.print(request.getContextPath());
      out.write("/replies/board/pds/\"+reply_no,\r\n");
      out.write("      type:\"delete\",\r\n");
      out.write("      data:JSON.stringify(sendData),\r\n");
      out.write("      headers:{\r\n");
      out.write("         \"Content-Type\" : \"application/json\",\r\n");
      out.write("         \"X-HTTP-Method-Override\":\"DELETE\"\r\n");
      out.write("      },\r\n");
      out.write("      success:function(page){\r\n");
      out.write("         alert(\"삭제되었습니다.\");\r\n");
      out.write("      },\r\n");
      out.write("      error:function(error){\r\n");
      out.write("         alert('삭제 실패했습니다.');      \r\n");
      out.write("      },\r\n");
      out.write("      complete:function(){\r\n");
      out.write("          $('#exampleModal5').modal('hide');\r\n");
      out.write("         getPage(\"");
      out.print(request.getContextPath());
      out.write("/replies/board/pds/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${post.post_no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\"+replyPage);\r\n");
      out.write("      }\r\n");
      out.write("   });\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/board/pds/pdsDetail.jsp(33,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${post.post_writer eq loginUser.member_id || loginUser.member_role eq 'ADMIN'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("<button class=\"btn btn-outline\" id=\"modifyBtn\" style=\"margin-left:4px; border:1px solid #dddddd;\">\r\n");
          out.write("\t\t\t\t\t\t\t\t<span>수정</span>\r\n");
          out.write("\t\t\t\t\t\t\t</button>\r\n");
          out.write("\t\t\t\t\t\t\t<button class=\"btn btn-outline\" style=\"border:1px solid #dddddd;\" id=\"removeBtn\">\r\n");
          out.write("\t\t\t\t\t\t\t\t<span>삭제</span>\r\n");
          out.write("\t\t\t\t\t\t\t</button>\r\n");
          out.write("\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /WEB-INF/views/board/pds/pdsDetail.jsp(90,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${post.post_writer eq loginUser.member_id || loginUser.member_role eq 'ADMIN'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("<div>\r\n");
          out.write("\t\t\t\t\t\t<input type=\"text\" placeholder=\"댓글을 작성해주세요.\" id=\"newreply_content\" name=\"newreply_content\" class=\"form-control\" style=\"display: inline-block; margin:0 auto; width:90%;\" maxlength=\"10\" />\r\n");
          out.write("\t\t\t\t\t\t<button class=\"submit button button-box button-round button-primary\" id=\"replyAddBtn\" style=\"position:absolute; right:42px; bottom:-2px;\">\r\n");
          out.write("\t\t\t\t\t\t\t<i class=\"zmdi zmdi-mail-send\"></i>\r\n");
          out.write("\t\t\t\t\t\t</button>\r\n");
          out.write("\t\t\t\t\t</div>\t\r\n");
          out.write("\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }
}
